### ISSUE TITLE
AccesPolicy.findUsers only works with one mail address

### ISSUE THREAD

**Issue by forki** [CompositionalIT/farmer#288] opened 2020-07-20 11:36 UTC
AccesPolicy.findUsers only works with one mail address.

Workaround: call it in a loop:

![image](https://user-images.githubusercontent.com/57396/87933676-feaa6200-ca8d-11ea-8573-88877521f54f.png)

**Comment by isaacabraham** [comment] 2020-07-20 19:08
Can't reproduce. Have tested it two valid email addresses and with one valid and one invalid. Both times I get results back.

**Comment by forki** [comment] 2020-07-20 19:10
Weird

**Comment by isaacabraham** [comment] 2020-07-20 19:12
The query we send to az is basically as follows:

```bash
ad user list --filter "email1@company.com or email2@company.com or email3@company.com or email4@company.com or email5@company.com"
```

Can you try create that yourself and testing that out? Maybe you have an older version of az which has a bug in it or something?

**Comment by isaacabraham** [comment] 2020-07-20 19:13
I'm testing using 2.7.0

**Comment by isaacabraham** [comment] 2020-08-08 13:25
@forki can you confirm this is still occurring? Otherwise I can close this.

**Comment by forki** [comment] 2020-08-09 08:12
It's still happening. But I have a workaro, so feel free to close. Thx

Isaac Abraham <notifications@github.com> schrieb am Sa., 8. Aug. 2020,
15:25:

**Comment by isaacabraham** [comment] 2020-08-30 16:25
@forki I'd like to get to the bottom of this. Can you confirm that the query above that I provided doesn't work for you?

**Comment by isaacabraham** [comment] 2020-10-21 23:27
Closing.

**Closed by isaacabraham** 2020-10-21 23:27 UTC
Labels: bug, needs-more-info
