### ISSUE TITLE
Return DeploymentResult in quick deploy instead of unit

### ISSUE THREAD

**Issue by tforkmann** [CompositionalIT/farmer#107] opened 2020-04-14 14:44 UTC
Hi there,

for the fullDeploy you receive the DeploymentResult response back after the deployment.
Would be nice to get the DeploymentResult back for the quick deploy as well instead of returning just an unit.

Would be very cool if this can be added.

Thanks in advance

**Comment by isaacabraham** [comment] 2020-04-14 16:57
I've done a (big) refactoring on the deployment side and we will use Azure CLI from now on, all the time. I've written code to allow us to reason more easily about Az CLI commands etc. as well. @viktorvan would you mind testing out the azure-cli branch on linux to ensure that things are still working? All the script code is gone now - instead we just call az directly.

**Comment by isaacabraham** [comment] 2020-04-14 16:59
Forgot to say - this branch also will return the outputs as a map :-)
```fsharp
let myStorage = storageAccount {
    name "isaacssuperstore"
}

let deployment = arm {
    location NorthEurope
    add_resource myStorage
    output "generated_key" myStorage.Key
}

/// Result<Map<string, string>, string>
let outputs = deployment |> Deploy.execute "my-resource-group"
0
```
`outputs` contains `[ "generated_key", "<the storage key"> ]`

**Comment by viktorvan** [comment] 2020-04-14 17:49
Oh, that’s great to switch to azure cli. This means you’ll close the issue to remove the dependency to FsHttp as well. And you don’t even have to replace it with anything but the azure cli, nice. 

I can try out the azure-cli branch later tonight, on mac though, but it should work the same as for linux I think.

**Comment by viktorvan** [comment] 2020-04-14 19:05
Ok, @isaacabraham I tried running the azure-cli branch and ran into an issue. Feel free to move this discussion to another issue if it's not appropriate to continue here...

Deploy.execute fails when checking azure logged in status:

```bash
Checking Azure CLI logged in status... az: error: unrecognized arguments: > .farmer/output.txt
usage: az [-h] [--verbose] [--debug] [--output {json,jsonc,table,tsv,yaml,none}]
          [--query JMESPATH]
          {account} ...
```

It is the use of `>` in the Arguments for ProcessStartInfo that is not working as expected. Although I can run the command `az account show > .farmer/output.txt` directly in my shell without any issues. 

A workaround that worked for me was to modify Deploy.execute as follows:

```fsharp
open System.Text
/// Executes a generic AZ CLI command.
let executeAz arguments =
    let p =
        ProcessStartInfo(
            FileName = "az",
            Arguments = arguments,
            UseShellExecute = false,
            CreateNoWindow = true,
            RedirectStandardOutput = true,
            WindowStyle = ProcessWindowStyle.Hidden)
        |> Process.Start
    p.WaitForExit()

    let sb = StringBuilder()

    while not p.StandardOutput.EndOfStream do
        p.StandardOutput.ReadLine() |> sb.AppendLine |> ignore

    let response = sb.ToString()
    match p.ExitCode with
    | 0 -> Ok response
    | _ -> Error response
```

That is, I have removed the redirect to file from `Arguments`, set `UseShellExecute = false` and `RedirectStandardOutput = true`.
And instead of writing to file I just used a StringBuilder().

Maybe there's a better solution, but this worked for me at least. :)

**Comment by tforkmann** [comment] 2020-04-14 19:45
Hi Isaac,

thanks for the fast implementation.
It worked perfectly for me:
![image](https://user-images.githubusercontent.com/4168951/79267267-3014ff80-7e99-11ea-8f31-85f2401a9cbc.png)

Thanks!

**Comment by isaacabraham** [comment] 2020-04-14 20:55
@viktorvan firstly thank you for testing. I suspected that this might happen. I tested with `UseShellExecute` set to false - the problem is then that the command `az` on Windows doesn't work - you have to use `az.cmd` and even then it doesn't work because it can't find Python. The only option is to provide the full path to `az` which seems pretty fragile to me.

I'll install WSL here and see if I can test both Windows and Linux out - otherwise this is going to be a right pain to sort out.

**Comment by isaacabraham** [comment] 2020-04-14 20:55
Hmmm. Alternatively we can just have different mechanisms for shelling out based on whether you're on Windows or Linux.

**Comment by isaacabraham** [comment] 2020-04-14 22:12
@viktorvan I've tried to integrate the Linux and Windows mechanisms into one call (with a pattern match on OS, as we did previously with the batch file) using your sample as a basis for the Linux implementation. Can you give it another go?

**Comment by viktorvan** [comment] 2020-04-15 06:21
I think you just missed to `p.WaitForExit()` in `executeAzLinux` before reading from `p.StandardOutput`, if I add that it works.

**Closed** 2020-04-15 07:29 UTC
