### ISSUE TITLE
Automatic documentation deployment

### ISSUE THREAD

**Issue by isaacabraham** [CompositionalIT/farmer#84] opened 2020-04-01 13:32 UTC
I have no clue how to do this but I imagine that it's possible to automatically push Hugo sites to github io?

**Comment by khalidabuhakmeh** [comment] 2020-04-01 15:15
Here are the steps necessary:

1. GitHub Action to build on PR / Tag / Or Whatever
    1. Push results into a "docs" branch or a directory on "master"
2. Set up repository settings to look for branch or docs directory

**Comment by khalidabuhakmeh** [comment] 2020-04-01 15:34
https://github.com/peaceiris/actions-hugo

**Comment by SeanKilleen** [comment] 2020-04-04 21:57
Picking this one up.

**Comment by SeanKilleen** [comment] 2020-04-04 22:15
Note: I've merged the Github Actions workflow to master but it's not yet appearing in the UI. 

Before merging my doc change (just a simple local README that won't change contents), I'm going to make sure the action either shows up or that I confirm that it shouldn't yet.

**Comment by SeanKilleen** [comment] 2020-04-04 22:20
Confirmed [here](https://github.community/t5/GitHub-Actions/Github-Action-Not-Showing/td-p/52635) that the action should show up after the first run.

That means I'm going to go ahead and get #88 merged which should kick off the action without changing any docs content.

**Comment by SeanKilleen** [comment] 2020-04-04 22:35
OK, I made another tweak to the docs branch after updating this workflow.

It has not run yet. My guess is it's on some sort of a timeline so I'm going to wait for a little bit before assuming something's wrong. 

I'll check in on it periodically. Feel free to ping me in a little bit if something's gone wrong.

Even if something is wrong in the process, I can force push my local output to the `gh-pages` branch and fix it up.

**Comment by SeanKilleen** [comment] 2020-04-05 01:43
FYI, I have reached out to the GitHub community about this because I am unsure why the Action workflow isn't being kicked off. My understanding is that as long as the `gh-pages` branch exists and is set for github pages (and it is), the `GITHUB_SECRET` token is what we should be using.

Link in case anyone wants to follow along: https://github.community/t5/GitHub-Actions/GitHub-Action-not-starting/td-p/52767

**Comment by managedkaos** [comment] 2020-04-05 21:59
Hi @SeanKilleen !  I saw your request and wanted to help out.

I looks like your workflow is not getting triggered because the `docs` branch didn't have a workflow.  In fact, the worflow file is only  on the `master` branch.

I submitted a PR: https://github.com/CompositionalIT/farmer/pull/94

Hope that it helps!

-M

**Comment by SeanKilleen** [comment] 2020-04-05 22:21
@managedkaos thank you! I was under the impression that a workflow on the master branch was possible to run on all branches; I thought that's why there is a branch specification in the workflow in the first place.

It's a lot to ask since if you already fixed the problem :) but can you point me to any relevant docs / info? I looked everywhere to answer that question but assumed since I could scope to branches, the workflow didn't need to be on a specific branch.

**Comment by SeanKilleen** [comment] 2020-04-05 22:35
Update: great! With that hiccup behind us, all we have to do now is make a few final tweaks and then we should be good to watch this thing run all the way through.

**Comment by SeanKilleen** [comment] 2020-04-05 22:49
Success! 🎉 

After @managedkaos added the workflow into the `docs` branch, I had one last tweak: to remove the `public` folder being set up as a sub-module (not sure why it was set up that way).

I ran `git rm --cached public` and committed the result on the `docs branch` via dfe22d9e9ddd09eaf16517c890d47c06690e77d5 and the action has run successfully.

Next up: Making a minor tweak to the docs and watching it propagate to the live site.

**Comment by SeanKilleen** [comment] 2020-04-05 22:54
This is now resolved:

✅ docs branch changes will be automatically built and published to `gh-pages` branch and served.
✅ README on the docs branch describes the behavior.

I discussed with @isaacabraham different directions that the project might want to go:

* Could move docs to a separate repo
* Could move docs into a folder within `master`
* Could think about utilizing tooling that allows for multiple versions of documentation.

All of these have various trade-offs but for now, the automated builds are working with the initial setup. 👍

**Closed by SeanKilleen** 2020-04-05 22:54 UTC

**Comment by managedkaos** [comment] 2020-04-05 23:18
Glad it worked out.  See step four here:
https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#creating-a-workflow-file

   1.

   Commit your changes in the workflow file to the branch where you want
   your workflow to run.
