### ISSUE TITLE
Support for Log Analytics In Farmer 

### ISSUE THREAD

**Issue by Mohammd19** [CompositionalIT/farmer#326] opened 2020-09-02 17:55 UTC
I'm curious if anyone working on adding Log Analytics to Farmer, if not I'm more than happy to do it :)

**Comment by isaacabraham** [comment] 2020-09-08 21:23
@Mohammd19 that would be very welcome :-)

**Comment by isaacabraham** [comment] 2020-09-08 21:32
Closing as duplicate of #262.

**Closed by isaacabraham** 2020-09-08 21:32 UTC
Labels: arm-resource
